import org.jetbrains.kotlin.gradle.dsl.JvmTarget

apply plugin: 'com.android.application'

kotlin {
    compilerOptions {
        freeCompilerArgs.add("-Xexplicit-backing-fields")
        jvmTarget.set(JvmTarget.JVM_17)
    }
}

android {
    namespace "com.steevsapps.idledaddy"
    compileSdkVersion 37 // Android 17

    defaultConfig {
        applicationId "com.steevsapps.idledaddy"
        minSdkVersion 27 // Android 8
        targetSdkVersion 36 // Android 16
        versionCode 96
        versionName "2.0.50"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildFeatures {
        buildConfig true
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            buildConfigField 'String', 'SteamApiKey', steamApiKey
        }

        debug {
            buildConfigField 'String', 'SteamApiKey', steamApiKey
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
        coreLibraryDesugaringEnabled true
    }
}

ext {
    supportLibraryVersion = "27.1.1"
}

configurations.configureEach {
    // Don't cache changing modules at all.
    resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
}

dependencies {
    coreLibraryDesugaring libs.desugar.jdk.libs
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    androidTestImplementation('androidx.test.espresso:espresso-core:3.1.0', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    implementation(libs.bundles.javasteam) {
        changing = true
    }
    implementation libs.bundles.androidx.ui
    implementation libs.bundles.legacy
    implementation libs.bundles.network
    implementation libs.glide
    implementation libs.jsoup
    implementation libs.lifecycle.extensions
    implementation libs.zxing.core

    testImplementation libs.junit
}